name: py37-this_is_a_dumb_name_you_should_change_it
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - python=3.7
  - ipython
  - jupytext
  - notebook
  - jupyterlab
  - seaborn
  - altair
  - plotly
  - rpy2
  - cython
  - dask
  - lifelines
  - pandas-profiling
  - jupyter_contrib_nbextensions
  - pip:
    - bamboolib
    - pyforest
