name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipywidgets
  - jupyter_contrib_nbextensions
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - lifelines
  - pandas-profiling

name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib


dependencies:
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - fortran-magic 
  - cython
  - rpy2
  - pip
  - pip:
      - julia
      - cffi_magic
numpy
matplotlib


numpy==1.16.*
matplotlib==3.*
seaborn==0.8.1
pandas


traitlets>=4.3.1
ipython
pandas
vdom
jupyterlab_launcher>=0.5.0
